"""improve models

Revision ID: 620250a0ba45
Revises: 695384db7893
Create Date: 2026-02-23 11:27:51.668720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '620250a0ba45'
down_revision: Union[str, Sequence[str], None] = '695384db7893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gifts', sa.Column('photo', sa.String(length=255), nullable=True))
    op.alter_column('gifts', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.add_column('wishlist_accesses', sa.Column('role', sa.Enum('viewer', 'editor', name='wishlistrole'), nullable=False))
    op.drop_column('wishlist_accesses', 'wishlist_role_enum')
    op.add_column('wishlists', sa.Column('visibility', sa.Enum('public', 'link_only', 'private', name='wishlistvisibility'), nullable=False))
    op.drop_column('wishlists', 'wishlist_visibility_enum')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlists', sa.Column('wishlist_visibility_enum', postgresql.ENUM('public', 'link_only', 'private', name='wishlistvisibility'), autoincrement=False, nullable=False))
    op.drop_column('wishlists', 'visibility')
    op.add_column('wishlist_accesses', sa.Column('wishlist_role_enum', postgresql.ENUM('viewer', 'editor', name='wishlistrole'), autoincrement=False, nullable=False))
    op.drop_column('wishlist_accesses', 'role')
    op.alter_column('gifts', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('gifts', 'photo')
    # ### end Alembic commands ###
