"""improve models

Revision ID: 695384db7893
Revises: dabcdb1cd8c0
Create Date: 2026-02-23 11:11:22.643419

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "695384db7893"
down_revision: Union[str, Sequence[str], None] = "dabcdb1cd8c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "gifts",
        "price",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "gifts", "price", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
    )
    # ### end Alembic commands ###
