"""improve models

Revision ID: 6b1b35d43510
Revises: 620250a0ba45
Create Date: 2026-02-23 12:15:25.068453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b1b35d43510'
down_revision: Union[str, Sequence[str], None] = '620250a0ba45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wishlist_accesses', 'invited_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wishlist_accesses', 'invited_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
