"""improve models

Revision ID: b892fdd83a2d
Revises: 6b1b35d43510
Create Date: 2026-02-23 12:17:30.279633

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "b892fdd83a2d"
down_revision: Union[str, Sequence[str], None] = "6b1b35d43510"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
