"""improve models

Revision ID: dabcdb1cd8c0
Revises: afc91cf24d91
Create Date: 2026-02-23 11:08:26.349546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dabcdb1cd8c0'
down_revision: Union[str, Sequence[str], None] = 'afc91cf24d91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gifts', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('gifts', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    op.drop_column('users', 'password')
    op.add_column('wishlist_accesses', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('wishlist_accesses', sa.Column('wishlist_role_enum', sa.Enum('viewer', 'editor', name='wishlistrole'), nullable=False))
    op.drop_column('wishlist_accesses', 'role')
    op.add_column('wishlists', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('wishlists', sa.Column('wishlist_visibility_enum', sa.Enum('public', 'link_only', 'private', name='wishlistvisibility'), nullable=False))
    op.create_index(op.f('ix_wishlists_owner_id'), 'wishlists', ['owner_id'], unique=False)
    op.drop_column('wishlists', 'visibility')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlists', sa.Column('visibility', postgresql.ENUM('public', 'link_only', 'private', name='wishlistvisibility'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_wishlists_owner_id'), table_name='wishlists')
    op.drop_column('wishlists', 'wishlist_visibility_enum')
    op.drop_column('wishlists', 'created_at')
    op.add_column('wishlist_accesses', sa.Column('role', postgresql.ENUM('viewer', 'editor', name='wishlistrole'), autoincrement=False, nullable=False))
    op.drop_column('wishlist_accesses', 'wishlist_role_enum')
    op.drop_column('wishlist_accesses', 'created_at')
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('users', 'hashed_password')
    op.drop_column('gifts', 'created_at')
    op.drop_column('gifts', 'price')
    # ### end Alembic commands ###
